### ISSUE TITLE
Rstudio server viewer plot autosize

### ISSUE THREAD

**Issue by Liripo** [vegawidget/vegawidget#219] opened 2023-05-09 14:27 UTC
![image](https://github.com/vegawidget/vegawidget/assets/54770415/065cdc1c-f330-442e-87c1-791cbeca749f)

In Rstudio viewer, the default width and height seem to be too small, is there a way to behave like ggplot2 without having to specify the width and height by myself.

**Comment by ijlyttle** [comment] 2023-12-29 19:25
Sorry for delay - I don't think there is a way to do this. It stems from the [sizing policy](https://www.htmlwidgets.org/develop_sizing.html) - in Vega, you can let the layout drive the size, or the size drive the layout. I think there are more situations where you want to control the layout.

I'll leave this open as a long-term issue.

**Comment by ijlyttle** [comment] 2023-12-29 19:27
Looking closer, closing this as a duplicate of #60.

**Closed by ijlyttle** 2023-12-29 19:27 UTC
Labels: long-term
